# Generated by Django 3.2.6 on 2023-05-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'администратор'), ('user', 'пользователь')], default='user', max_length=15)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
